FROM gentoo/stage3:latest

WORKDIR /overlay

RUN emerge-webrsync

COPY . .

RUN mkdir -p /etc/portage/repos.conf && \
    echo -e "[koala-clash-overlay]\nlocation = /var/db/repos/koala-clash-overlay\nmasters = gentoo\nauto-sync = no" > /etc/portage/repos.conf/koala-clash-overlay.conf

RUN mkdir -p /etc/portage/package.accept_keywords && \
    echo "net-proxy/koala-clash ~amd64" > /etc/portage/package.accept_keywords/koala-clash

RUN mkdir -p /etc/portage/package.license && \
    echo "net-proxy/koala-clash GPL-3" > /etc/portage/package.license/koala-clash

RUN emerge -p net-proxy/koala-clash
